version: '3.7'

services:
  spring-app:
    build:
      context: ./spring-app
    container_name: spring-app
    ports: 
      - '8080:8080'
    networks:
      - default-network
  
  react-app:
    build:
      context: ./react-app
      args:
        REACT_APP_SPRING_APP_HOST: # text here your IPv4 on your LAN to access through different devices on same network
    container_name: react-app
    depends_on:
      - spring-app
    ports: 
      - '3000:3000'
    networks:
      - default-network

networks:
  default-network:
    driver: bridge